spring:
  config:
    activate:
      on-profile: local
  datasource:
    username:
    password:
    url:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: root
    password:
    url:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
---
