spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id:
            client-secret:
            redirect-uri:
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

  jwt:
    secret: